[options]
# 📂 Rutas donde Odoo busca los módulos y aplicaciones para cargar.
# Incluye los del sistema base (/usr/...) y tus carpetas de módulos personalizados (/mnt/...).
addons_path = /mnt/extra-addons,/mnt/custom-addons,/usr/lib/python3/dist-packages/odoo/addons

# 💾 Carpeta interna donde Odoo guarda archivos persistentes (como imágenes de productos, adjuntos y sesiones).
data_dir = /var/lib/odoo

# 🔑 Contraseña maestra de seguridad requerida para crear, duplicar, respaldar o borrar bases de datos desde la web.
admin_passwd = admin_secret_password

# 🌐 Activa el modo proxy. Le avisa a Odoo que tiene un proxy inverso (Traefik) al frente encargándose del SSL/HTTPS.
proxy_mode = True

# ⚙️ Número de hilos de procesamiento (Python Workers) dedicados a atender peticiones simultáneas de los usuarios.
workers = 2

# ⏱️ Hilos dedicados exclusivamente a ejecutar tareas automáticas en segundo plano (como enviar correos o calcular inventario).
max_cron_threads = 1

# 🟢 CONFIGURACIÓN DE CONEXIÓN CON LA BASE DE DATOS (Agregada para resolver el error 502)
# ==========================================================================================

# 🗺️ Indica el nombre del contenedor de la base de datos dentro de Docker con el que Odoo debe comunicarse.
db_host = db_prod

# 👤 Nombre de usuario de PostgreSQL configurado en tu docker-compose para autenticar la conexión.
db_user = odoo

# 🔒 Contraseña correspondiente a ese usuario para autorizar el acceso y la creación de tablas.
db_password = odoo