[options]
# 📂 Rutas donde Odoo de pruebas busca los módulos.
addons_path = /mnt/extra-addons,/mnt/custom-addons,/usr/lib/python3/dist-packages/odoo/addons

# 💾 Carpeta interna para archivos temporales e imágenes en el entorno de pruebas.
data_dir = /var/lib/odoo

# 🧪 Contraseña maestra exclusiva para gestionar las bases de datos de prueba.
admin_passwd = admin_test_password

# 🌐 Activa el modo proxy para que Traefik gestione el tráfico de pruebas.
proxy_mode = True

# 🧪 CONFIGURACIÓN DE CONEXIÓN CON LA BASE DE DATOS DE STAGING (Sincronizado con tu YAML)
# ==========================================================================================

# 🗺️ DEBE COINCIDIR: El nombre del servicio del segundo contenedor en tu YAML es "db_test"
db_host = db_test

# 👤 DEBE COINCIDIR: Sacado de POSTGRES_USER=odoo
db_user = odoo

# 🔒 DEBE COINCIDIR: Sacado de POSTGRES_PASSWORD=odoo
db_password = odoo