[options]
addons_path = /mnt/extra-addons,/mnt/custom-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
# Buena práctica: Usa una contraseña diferente aquí si quieres
admin_passwd = admin_test_password
proxy_mode = True