services:
  odoo:
    image: odoo:18.0
    container_name: odoo_juguete
    depends_on:
      - db
    networks:
      - proxy-network
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ../../custom-addons:/mnt/custom-addons
      - ./config:/etc/odoo
      - ./data:/var/lib/odoo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.juguete.rule=Host(`jugueteria.32.194.128.10.nip.io`)"
      - "traefik.http.routers.juguete.entrypoints=websecure"
      - "traefik.http.routers.juguete.tls.certresolver=myresolver"

  db:
    image: postgres:15
    container_name: db_juguete
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      - proxy-network
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  proxy-network:
    external: true